FROM        --platform=$BUILDPLATFORM alpine:3.16

LABEL       author="Torsten Widmann" maintainer="info@goover.de"

RUN         apk add --update --no-cache ca-certificates tzdata \
				&& adduser -D -h /home/container container

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

COPY        ./../entrypoint.sh /entrypoint.sh
CMD         [ "/bin/ash", "/entrypoint.sh" ]
