FROM        --platform=$BUILDPLATFORM alpine:latest

LABEL       org.opencontainers.image.authors="info@goover.de"
LABEL       org.opencontainers.image.source="https://github.com/gOOvER/own-pterodactyl-images"
LABEL       org.opencontainers.image.licenses=AGPL-3.0-or-later
LABEL       org.opencontainers.image.description "Docker image for Pelican Hosting Panel and Pterodactyl"LABEL       org.opencontainers.image.description Dockerimage for Pelican Hosting Panel and Pterodactyl

RUN         apk add --update --no-cache ca-certificates curl unzip tar git jq wget
